### ISSUE TITLE
Any plans for a TypeScript definition?

### ISSUE THREAD

**Issue by glaucomorais** [auth0-community/socketio-jwt#101]
I'm working with NodeJS + Socket.io with TypeScript and couldn't get a definition file for the module.
Any plans on the `.d.ts` file? Anyone working on this?

**Comment by mleanos** [comment]
Would love this as well!

**Comment by Root-Core** [comment]
Just check out my fork.
I hope the definitions are usable. They could need some additional documentation (no time yet, PRs welcome).

There are some other changes as well, all PRs here are merged.
Some feedback would be nice.

https://github.com/Root-Core/socketio-jwt

**Comment by icharge** [comment]
@Root-Core I'm looking for it. Thank you
