### ISSUE TITLE
What does timeout mean

### ISSUE THREAD

**Issue by timeswind** [auth0-community/socketio-jwt#103]
``` javascript
io.sockets
  .on('connection', socketioJwt.authorize({
    secret: 'your secret or public key',
    timeout: 15000 // 15 seconds to send the authentication message
  })).on('authenticated', function(socket) {
    //this socket is authenticated, we are good to handle more events from it.
    console.log('hello! ' + socket.decoded_token.name);
  });
```

**Comment by sisou** [comment]
It means the browser has up to 15 seconds to send the `authenticate` message with the token after the websockets connection has been established.

15 seconds is a bit much, as I would think that the authorisation message should be the first one to be sent over the connection, thus only really needing 1 second (or 5 seconds for a slow connection maybe?).
