### ISSUE TITLE
JWT expired is not being thrown

### ISSUE THREAD

**Issue by olegmdev** [auth0-community/socketio-jwt#124]
Once it's successfully authorized, I get the decoded data on my end. However as soon as token is expired, I continue successfully getting all my messages with my decoded data (probably bc of using an adapter).

Is that the normal behavior and I need to `verify` this token on every socket message or there is something wrong with it?

**Comment by cedriccouret** [comment]
Hi @olegmdev ,
did you get further information on this topic ?

Thanks.

**Comment by olegmdev** [comment]
Hi @cedriccouret, unfortunately no. 
I did it my way by adding token verification step in every socket event handler.

**Comment by cedriccouret** [comment]
Thanks for your reply, I eventually went the same road :-)

**Comment by razor9999** [comment]
hi @olegmdev could u give some sample code for adding token verification step in every socket event handler
