### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by camsjams** [auth0-community/socketio-jwt#130]
It appears many of the examples from [blog posts](https://auth0.com/blog/auth-with-socket-io/) don't work anymore, and there hasn't been any migration of the example usage of this library (see https://github.com/auth0/socketio-jwt/commit/9b644e22cedd7929a3717e181a2a3f0c1871710f).

The question is, is the auth0 team still concerned with maintaining this library?

Thanks!

**Comment by aaguiarz** [comment]
Hi,

No, it's not being maintained, we deprecated it 4 months ago (https://github.com/auth0-community/socketio-jwt/tree/master/example).

Regards,

Andres

**Comment by camsjams** [comment]
The example - yes I saw that thanks.

But are you also stating that the repository/library is no longer maintained?

**Comment by aaguiarz** [comment]
It's no longer maintained/supported by Auth0. 

I just clarified that in the Readme

**Comment by camsjams** [comment]
Thanks!
