### ISSUE TITLE
Invalid algorithm

### ISSUE THREAD

**Issue by m1ch34lj0hns0n** [auth0-community/socketio-jwt#145]
# Issue Report
### Description

On attempt of authenticating a websocket I am receiving the response:

> 83:44{"message":"invalid algorithm","code":"invalid_token","type":"UnauthorizedError"}

I have a nodejs service running locally on port 4002 with the following code:
```
const app = express();
const server = http.createServer(app);
const io = SocketIO(server);
const port = 4002;

io.use(socketioJwt.authorize({
    secret: new Buffer('auth0 Client Secret', 'base64'),
    handshake: true
}));

io.on('connection', async socket => {
    // console.log('hello! ', socket.decoded_token.name);
    socket.emit('data', await routes.emitDashboard());
});
```
I also have a separate react application on port 4001:
```
    state = {
        services: null,
        endpoint: 'localhost:4002'
    };

    /**
     * ComponentDidMount
     * @returns {void}
     */
    componentDidMount() {
        const {auth} = this.props;
        const {endpoint} = this.state;
        const socket = io(endpoint, {
            query: `token=${auth.getAccessToken()}`
        });
        socket.on('data', services => this.setState({services}));
    }
```

### Expected behaviour

I expect the websocket to return an object called by routes.emitDashboard()

### Actual behaviour 

> 83:44{"message":"invalid algorithm","code":"invalid_token","type":"UnauthorizedError"}

### Steps to reproduce the problem

As above.

### Language / Framework Versions

1. **Language used:** JavaScript
2. **Framework used:** express/react

Any help would be greatly appreciated as I'm not very well versed on auth/sockets.

**Comment by m1ch34lj0hns0n** [comment]
After some minor debugging I can see that it is:

> jwt.verify(token, secret, options, onJwtVerificationReady)

which is returning the error to onJwtVerificationReady and from further reading I believe that as I am only passing my secret the correct algorithm should be H256:

```
io.use(socketioJwt.authorize({
    secret: 'auth0 Client Secret',
    algorithms: ['H256'],
    handshake: true
}));
```

After updating the object to use what I think is the correct algorithm I am now receiving another error:

> Error: PEM_read_bio_PUBKEY failed

**Comment by m1ch34lj0hns0n** [comment]
Resolved.

**Comment by jjarrett21** [comment]
@m1ch34lj0hns0n did you find an answer for this?
