### ISSUE TITLE
Socket Data tranmission is not working for android alone

### ISSUE THREAD

**Issue by Karthik4dec** [auth0-community/socketio-jwt#52]
In Android connection establishment working perfectly for me but data transfer through socket is not working(i.e socket emit and on) but it is working perfectly in web

This issue only persist in android.

Sorry for my English, And Thanks in Advance

**Comment by zouhenry** [comment]
What version of android are you using? I am using Cordova with android sdk version 22 (kitkat) and it works fine. 
I am also using "ws" protocol instead of http.

    ws://localhost:3000
